from __future__ import annotations
import json
import secrets
import shutil
import socket
import sys
import webbrowser
from pathlib import Path

from flask import Flask, jsonify, request, Response

from vibemonitor import summarizer
from vibemonitor.push import PushNotifier

_STATIC_DIR = Path(__file__).parent / "static"

# Where the bridge expects its config: bridge/config.toml (next to vibemonitor/).
DEFAULT_CONFIG_PATH = Path(__file__).parent.parent / "config.toml"

# Random-word pool for a friendly default ntfy topic suffix.
_TOPIC_WORDS = (
    "otter", "willow", "comet", "harbor", "lumen", "pixel", "ember", "cedar",
    "marble", "quartz", "nimbus", "fjord", "cobalt", "sprout", "thistle", "raven",
)

# Default thresholds — written verbatim so a fresh config has the documented values.
_DEFAULT_THRESHOLDS = {"working_sec": 60, "waiting_ttl_sec": 1800, "gone_ttl_sec": 14400}


# --------------------------------------------------------------------------- #
# TOML serialization (hand-rolled — stdlib has a reader but no writer).
# --------------------------------------------------------------------------- #

def _toml_value(v) -> str:
    """Serialize a scalar to TOML. Quote strings, lowercase booleans, pass numbers."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    # string: escape backslash and double-quote, emit a basic string
    s = str(v).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{s}"'


def _toml_inline_table(d: dict) -> str:
    """Serialize a flat dict as a TOML inline table: { k = v, ... }."""
    parts = [f"{k} = {_toml_value(v)}" for k, v in d.items()]
    return "{ " + ", ".join(parts) + " }"


def _b(form: dict, key: str, default: bool = False) -> bool:
    return bool(form.get(key, default))


def _s(form: dict, key: str) -> str | None:
    v = form.get(key)
    if v is None:
        return None
    v = str(v).strip()
    return v or None


def build_toml(form: dict) -> str:
    """Turn a settings dict into a valid config.toml string. Pure function.

    Recognized keys (all optional except `token`):
      token, host, port,
      enable_claude, enable_codex,
      summary_enabled, summary_model, summary_max_chars, openrouter_api_key,
      ha_webhook_url,
      push_provider, push_ntfy_url, push_pushover_token, push_pushover_user,
      push_escalate_sec,
      pricing  -> {model_id: {"input": float, "output": float}}

    Empty/disabled optional sections are omitted cleanly.
    """
    lines: list[str] = ["# VibeMonitor bridge configuration — generated by the setup wizard."]

    # ---- top level ----
    token = _s(form, "token") or secrets.token_urlsafe(12)
    lines.append(f"token = {_toml_value(token)}")
    lines.append(f"host = {_toml_value(_s(form, 'host') or '0.0.0.0')}")
    port = form.get("port", 5151)
    try:
        port = int(port)
    except (TypeError, ValueError):
        port = 5151
    lines.append(f"port = {port}")
    lines.append("")

    # ---- [thresholds] (defaults) ----
    lines.append("[thresholds]")
    for k, v in _DEFAULT_THRESHOLDS.items():
        lines.append(f"{k} = {v}")
    lines.append("")

    # ---- [poll] (defaults) ----
    lines.append("[poll]")
    lines.append("sessions_sec = 2.0")
    lines.append("usage_sec = 60.0")
    lines.append("costs_sec = 120.0")
    lines.append("summary_sec = 15.0")
    lines.append("")

    # ---- [providers] ----
    lines.append("[providers]")
    lines.append(f"claude = {_toml_value(_b(form, 'enable_claude', True))}")
    lines.append(f"codex = {_toml_value(_b(form, 'enable_codex', True))}")
    lines.append("")

    # ---- [summary] (only if enabled) ----
    if _b(form, "summary_enabled"):
        lines.append("[summary]")
        lines.append("enabled = true")
        model = _s(form, "summary_model") or "google/gemma-4-31b-it:free"
        lines.append(f"model = {_toml_value(model)}")
        max_chars = form.get("summary_max_chars", 2000)
        try:
            max_chars = int(max_chars)
        except (TypeError, ValueError):
            max_chars = 2000
        lines.append(f"max_chars = {max_chars}")
        lines.append("")

        api_key = _s(form, "openrouter_api_key")
        if api_key:
            lines.append("[openrouter]")
            lines.append(f"api_key = {_toml_value(api_key)}")
            lines.append("")

    # ---- [homeassistant] (only if a webhook url is set) ----
    ha_url = _s(form, "ha_webhook_url")
    if ha_url:
        lines.append("[homeassistant]")
        lines.append(f"webhook_url = {_toml_value(ha_url)}")
        lines.append("")

    # ---- [push] (only if configured for the selected provider) ----
    provider = (_s(form, "push_provider") or "ntfy").lower()
    ntfy_url = _s(form, "push_ntfy_url")
    po_token = _s(form, "push_pushover_token")
    po_user = _s(form, "push_pushover_user")
    push_configured = (provider == "ntfy" and ntfy_url) or (
        provider == "pushover" and po_token and po_user
    )
    if push_configured:
        lines.append("[push]")
        lines.append(f"provider = {_toml_value(provider)}")
        if provider == "ntfy":
            lines.append(f"ntfy_url = {_toml_value(ntfy_url)}")
        else:
            lines.append(f"pushover_token = {_toml_value(po_token)}")
            lines.append(f"pushover_user = {_toml_value(po_user)}")
        escalate = form.get("push_escalate_sec", 600)
        try:
            escalate = int(escalate)
        except (TypeError, ValueError):
            escalate = 600
        lines.append(f"escalate_sec = {escalate}")
        lines.append("")

    # ---- [pricing] (only if any rows) ----
    pricing = form.get("pricing")
    if isinstance(pricing, dict) and pricing:
        rows = {
            str(k): {"input": float(v["input"]), "output": float(v["output"])}
            for k, v in pricing.items()
            if isinstance(v, dict) and "input" in v and "output" in v
        }
        if rows:
            lines.append("[pricing]")
            for k, v in rows.items():
                lines.append(f"{_toml_value(k)} = {_toml_inline_table(v)}")
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #

def local_ip() -> str:
    """Best-effort LAN IP. Opens a UDP socket toward a public address (no packets
    actually sent) and reads the chosen local interface. Falls back to 127.0.0.1.
    Never raises."""
    s = None
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        return ip or "127.0.0.1"
    except Exception:
        return "127.0.0.1"
    finally:
        if s is not None:
            try:
                s.close()
            except Exception:
                pass


def _suggest_ntfy_topic() -> str:
    return f"vibemon-{secrets.choice(_TOPIC_WORDS)}-{secrets.token_hex(2)}"


def ha_snippets(ip: str, port: int, token: str) -> dict:
    """Ready-to-paste Home Assistant YAML, pre-filled with ip/port/token.

    Returns {"sensor": <rest+template yaml>, "automation": <webhook yaml>}.
    Mirrors the contract in README's Home Assistant section.
    """
    resource = f"http://{ip}:{port}/ha"
    sensor = f"""# configuration.yaml — poll the VibeMonitor bridge as a REST sensor.
sensor:
  - platform: rest
    name: VibeMonitor
    resource: {resource}
    headers:
      X-VibeMonitor-Token: "{token}"
    scan_interval: 10
    value_template: "{{{{ value_json.waiting_count }}}}"
    json_attributes:
      [claude_pct, codex_pct, claude_reset_min, waiting_count, working_count,
       any_waiting, longest_waiting_sec, capacity_status, stale_sec, waiting]

# Ready-made named entities derived from the REST sensor above.
template:
  - sensor:
      - name: Claude Usage
        unique_id: vibemonitor_claude_pct
        unit_of_measurement: "%"
        state: "{{{{ state_attr('sensor.vibemonitor', 'claude_pct') }}}}"
      - name: Codex Usage
        unique_id: vibemonitor_codex_pct
        unit_of_measurement: "%"
        state: "{{{{ state_attr('sensor.vibemonitor', 'codex_pct') }}}}"
      - name: VibeMonitor Waiting Count
        unique_id: vibemonitor_waiting_count
        state: "{{{{ state_attr('sensor.vibemonitor', 'waiting_count') }}}}"
  - binary_sensor:
      - name: VibeMonitor Needs Me
        unique_id: vibemonitor_needs_me
        device_class: problem
        state: "{{{{ state_attr('sensor.vibemonitor', 'any_waiting') | bool(false) }}}}"
      - name: VibeMonitor Bridge Online
        unique_id: vibemonitor_bridge_online
        device_class: connectivity
        state: >
          {{% set s = state_attr('sensor.vibemonitor', 'stale_sec') %}}
          {{{{ s is not none and s >= 0 and s < 30 }}}}
"""

    automation = """# configuration.yaml — react the instant a session needs you (webhook push).
# Set [homeassistant] webhook_url in config.toml to:
#   http://homeassistant.local:8123/api/webhook/vibemonitor-xxxxx
automation:
  - alias: VibeMonitor needs me
    trigger:
      - platform: webhook
        webhook_id: vibemonitor-xxxxx
        local_only: true
    action:
      - choose:
          - conditions: "{{ trigger.json.event == 'waiting' }}"
            sequence:
              - service: light.turn_on
                target: { entity_id: light.office }
                data: { rgb_color: [245, 166, 35] }   # amber
          - conditions: "{{ trigger.json.event == 'cleared' }}"
            sequence:
              - service: light.turn_off
                target: { entity_id: light.office }
"""
    return {"sensor": sensor, "automation": automation}


def _install_hooks_into_settings(token: str, url: str) -> dict:
    """Read ~/.claude/settings.json (or {}), merge our hooks, back up + write.
    Idempotent. Returns {"ok": bool, "message": str}. Mirrors install_hooks.main."""
    # install_hooks lives under bridge/hooks (not importable as a package), so add it.
    hooks_dir = Path(__file__).parent.parent / "hooks"
    if str(hooks_dir) not in sys.path:
        sys.path.insert(0, str(hooks_dir))
    import install_hooks  # noqa: E402

    settings_path = Path.home() / ".claude" / "settings.json"
    try:
        if settings_path.exists():
            settings = json.loads(settings_path.read_text(encoding="utf-8"))
            backup = settings_path.with_suffix(".json.vibemonitor.bak")
            shutil.copy(settings_path, backup)
        else:
            settings = {}
            settings_path.parent.mkdir(parents=True, exist_ok=True)
        command = install_hooks._our_command(hooks_dir, token, url)
        merged = install_hooks.merge_hooks(settings, command=command)
        settings_path.write_text(json.dumps(merged, indent=2), encoding="utf-8")
        return {"ok": True, "message": f"Installed hooks into {settings_path}"}
    except Exception as e:
        return {"ok": False, "message": f"Failed to install hooks: {e}"}


# --------------------------------------------------------------------------- #
# Flask app
# --------------------------------------------------------------------------- #

def create_setup_app(config_path: Path | None = None) -> Flask:
    """Setup-wizard Flask app. `config_path` is the target config.toml (injectable
    for tests); defaults to bridge/config.toml."""
    app = Flask(__name__)
    app.config["CONFIG_PATH"] = Path(config_path) if config_path else DEFAULT_CONFIG_PATH

    @app.get("/")
    def index():
        html = _STATIC_DIR / "setup.html"
        if not html.exists():
            return Response("setup.html not found", status=404, mimetype="text/plain")
        return Response(html.read_text(encoding="utf-8"), mimetype="text/html")

    @app.get("/api/defaults")
    def defaults():
        target = Path(app.config["CONFIG_PATH"])
        return jsonify({
            "token": secrets.token_urlsafe(12),
            "local_ip": local_ip(),
            "port": 5151,
            "ntfy_topic": _suggest_ntfy_topic(),
            "config_exists": target.exists(),
            "config_path": str(target),
        })

    @app.post("/api/test-openrouter")
    def test_openrouter():
        data = request.get_json(silent=True) or {}
        api_key = (data.get("api_key") or "").strip()
        model = (data.get("model") or "google/gemma-4-31b-it:free").strip()
        if not api_key:
            return jsonify({"ok": False, "error": "missing api_key"})
        result = summarizer.summarize("hello", api_key=api_key, model=model)
        return jsonify({"ok": result is not None})

    @app.post("/api/test-ntfy")
    def test_ntfy():
        data = request.get_json(silent=True) or {}
        ntfy_url = (data.get("ntfy_url") or "").strip()
        if not ntfy_url:
            return jsonify({"ok": False, "error": "missing ntfy_url"})
        ok = PushNotifier(provider="ntfy", ntfy_url=ntfy_url).send(
            "VibeMonitor", "Test push from setup"
        )
        return jsonify({"ok": bool(ok)})

    @app.post("/api/install-hooks")
    def install_hooks_endpoint():
        data = request.get_json(silent=True) or {}
        token = (data.get("token") or "").strip()
        url = (data.get("url") or "http://localhost:5151/hook").strip()
        if not token:
            return jsonify({"ok": False, "message": "missing token"})
        return jsonify(_install_hooks_into_settings(token, url))

    @app.post("/api/save")
    def save():
        form = request.get_json(silent=True) or {}
        target = Path(app.config["CONFIG_PATH"])
        toml_text = build_toml(form)
        try:
            target.parent.mkdir(parents=True, exist_ok=True)
            if target.exists():
                backup = target.with_suffix(".toml.bak")
                shutil.copy(target, backup)
            target.write_text(toml_text, encoding="utf-8")
        except Exception as e:
            return jsonify({"ok": False, "error": str(e)}), 500

        ip = (form.get("local_ip") or local_ip()).strip() or local_ip()
        try:
            port = int(form.get("port", 5151))
        except (TypeError, ValueError):
            port = 5151
        token = (form.get("token") or "").strip()
        next_steps = [
            f"Start the bridge:  python -m vibemonitor.main config.toml  "
            f"(serves http://{ip}:{port})",
            f"Provision the device with host={ip} port={port} token=<your token>",
            "Open the dashboard at http://%s:%d/ and paste the token once." % (ip, port),
        ]
        return jsonify({
            "ok": True,
            "path": str(target),
            "ha": ha_snippets(ip, port, token),
            "next_steps": next_steps,
        })

    return app


def main(argv: list[str] | None = None) -> int:
    app = create_setup_app()
    host, port = "127.0.0.1", 5152
    url = f"http://{host}:{port}/"
    print(f"VibeMonitor setup wizard: {url}")
    print("Opening your browser... (Ctrl+C to quit)")
    try:
        webbrowser.open(url)
    except Exception:
        pass
    app.run(host=host, port=port, debug=False, use_reloader=False)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
